.PHONY: 
update:
	git add easter_hours_prime.html
	git commit easter_hours_prime.html -m "updated easter_hours_prime.html for custom maintenance"

.PHONY: 
update_push:
	git add easter_hours_prime.html
	git commit easter_hours_prime.html -m "updated easter_hours_prime.html for custom maintenance"
	git push
.PHONY: 
push:
	git push
