.PHONY: 
update:
	git add java_project_ten.html
	git commit java_project_ten.html -m "updated java_project_ten.html for custom maintenance"

.PHONY: 
update_push:
	git add java_project_ten.html
	git commit java_project_ten.html -m "updated java_project_ten.html for custom maintenance"
	git push
.PHONY: 
push:
	git push





