.PHONY: 
update:
	git add java_project_three.html
	git commit java_project_three.html -m "updated java_project_three for custom maintenance"

.PHONY: 
update_push:
	git add java_project_three.html
	git commit java_project_three.html -m "updated java_project_three.html for custom maintenance"
	git push
.PHONY: 
push:
	git push


