.PHONY: 
update:
	git add java_project_nine.html
	git commit java_project_nine.html -m "updated java_project_nine.html for custom maintenance"

.PHONY: 
update_push:
	git add java_project_nine.html
	git commit java_project_nine.html -m "updated java_project_nine.html for custom maintenance"
	git push
.PHONY: 
push:
	git push





