.PHONY: 
update:
	git add java_project_six.html
	git commit java_project_six.html -m "updated java_project_six.html for custom maintenance"

.PHONY: 
update_push:
	git add java_project_six.html
	git commit java_project_six.html -m "updated java_project_.html for custom maintenance"
	git push
.PHONY: 
push:
	git push




