.PHONY: 
update:
	git add java_project_two.html
	git commit java_project_two.html -m "updated java_project_two for custom maintenance"

.PHONY: 
update_push:
	git add java_project_two.html
	git commit java_project_two.html -m "updated java_project_two.html for custom maintenance"
	git push
.PHONY: 
push:
	git push

